---
sudo: required

language: python
python: "2.7"

before_install:
 - sudo apt-get update -qq

addons:
  apt:
    packages:
    - python-pip

install:
  # Check ansible version
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # Install dependency
  - ansible-galaxy install resmo.ntp
  - ansible-galaxy install grycap.munge
  - ansible-galaxy install grycap.ssh

script:
  # Basic role syntax check
  - ansible-playbook tests/test-front.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test-wn.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
