---
  - name: Copy 'is_cluster_ready' file
    copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755

  - name: Set hostname
    command: hostname pbsserver

  - name: Update the /etc/hosts file
    shell: |
        for i in `seq 1 {{max_number_of_nodes}}`; do
          item="{{vnode_prefix}}${i}";
          grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item}.localdomain ${item}" >> /etc/hosts;
        done

    # PBS configuration Specific tasks
  - block:
    - name: Start 'pbs' service
      service: name=pbs state=started
      ignore_errors: yes

    - name: Execute qterm
      command: qterm
      ignore_errors: yes

    - name: Pip install pexpect
      pip: name=pexpect

    - name: Start pbs-server with minimal configuration
      expect:
        command: pbs_server -t create
        responses:
          "do you wish to continue.*": "y"

    - name: Execute qterm
      command: qterm
      ignore_errors: yes
    when: ansible_os_family == "RedHat"

  - name: Set torque nodenames
    copy:
      content: |
         {% for number in range(1, max_number_of_nodes|int + 1) %}
         {{vnode_prefix}}{{number}}
         {% endfor %}
      dest: "{{TORQUE_PATH}}/server_priv/nodes"
      force: yes

  - name: Restart '{{TORQUE_SERVICE}}' service
    service: name={{TORQUE_SERVICE}} state=restarted pattern=/usr/sbin/pbs_server
  - name: Start '{{TORQUE_SERVICE}}' service
    service: name={{TORQUE_SERVICE}} state=started pattern=/usr/sbin/pbs_server

  - name: Copy 'pbs_server.conf' file
    copy: dest=/tmp/pbs_server.conf src=pbs_server.conf mode=0755

  - name: Set torque conf
    shell: qmgr < /tmp/pbs_server.conf creates={{TORQUE_PATH}}/server_priv/queues/batch

  - name: Start '{{SCHED_SERVICE}}' service
    service: name={{SCHED_SERVICE}} state=started pattern=/usr/sbin/pbs_sched
    ignore_errors: yes

  # Many times TORQUE_SERVICE and SCHED_SERVICE do not start properly. Wait and test them again
  - name: Sleep 5 seconds
    command: sleep 5
  - name: Start '{{SCHED_SERVICE}}' service (again)
    service: name={{SCHED_SERVICE}} state=started pattern=/usr/sbin/pbs_sched
    ignore_errors: yes
  - name: Start '{{TORQUE_SERVICE}}' service (again)
    service: name={{TORQUE_SERVICE}} state=started pattern=/usr/sbin/pbs_server
