---
  - name: Copy 'is_cluster_ready' file
    copy:
      dest: /bin/is_cluster_ready
      content: "{{FILE}}"
      mode: 0755

  - name: Set hostname
    command: hostname torqueserver

  # Manage the /etc/hosts file
  - name: Update the /etc/hosts file
    shell: |
        for i in `seq 1 {{NNODES}}`; do
          item="{{vnode_prefix}}${i}";
          grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item}.localdomain ${item}" >> /etc/hosts;
        done

    # Torque configuration Specific tasks
  - name: Start 'trqauthd' service
    service: name=trqauthd state=started
    ignore_errors: yes

  - shell: pbs_server -t create
    when: ansible_os_family == "RedHat"
  - command: qterm
    when: ansible_os_family == "RedHat"

  - name: Set torque nodenames
    copy:
      content: |
         {% for number in range(1, NNODES|int + 1) %}
         {{vnode_prefix}}{{number}}
         {% endfor %}
      dest: "{{TORQUE_PATH}}/server_priv/nodes"
      force: yes

  - name: Restart '{{TORQUE_SERVICE}}' service
    service: name={{TORQUE_SERVICE}} state=restarted pattern=/usr/sbin/pbs_server
  - name: Start '{{TORQUE_SERVICE}}' service
    service: name={{TORQUE_SERVICE}} state=started pattern=/usr/sbin/pbs_server
  - name: Set torque conf
    shell: echo "{{pbs_server_conf}}" | qmgr creates={{TORQUE_PATH}}/server_priv/queues/batch

  - name: Start '{{SCHED_SERVICE}}' service
    service: name={{SCHED_SERVICE}} state=started pattern=/usr/sbin/pbs_sched

  # Many times TORQUE_SERVICE and SCHED_SERVICE do not start properly. Wait and test them again
  - name: Sleep 5 seconds
    command: sleep 5
  - name: Start '{{SCHED_SERVICE}}' service (again)
    service: name={{SCHED_SERVICE}} state=started pattern=/usr/sbin/pbs_sched
  - name: Start '{{TORQUE_SERVICE}}' service (again)
    service: name={{TORQUE_SERVICE}} state=started pattern=/usr/sbin/pbs_server
