---
  - name: Include "{{ansible_os_family}}" Torque recipe
    include: "{{ansible_os_family}}.yaml"
    
  - name: Set the PBS server name
    lineinfile:
      path: /etc/pbs.conf
      regexp: '^PBS_SERVER='
      line: PBS_SERVER=pbsserver


  - name: Create torque user and group
    user: name="{{torque_user}}" shell=/bin/bash system=yes    

  - name: Include "{{torque_type_of_node}}" Torque recipe
    include: "{{torque_type_of_node}}.yaml"
