---
  - name: Include "{{ansible_os_family}}" Torque recipe
    include: "{{ansible_os_family}}.yaml"
    
  - name: Set the PBS server name
    lineinfile:
      path: /etc/pbs.conf
      regexp: '^PBS_SERVER='
      line: PBS_SERVER=pbsserver
   
  - name: Create pbs user and group
    user: name="{{pbs_user}}" shell=/bin/bash system=yes    

  - name: Include "{{pbs_type_of_node}}" pbs recipe
    include: "{{pbs_type_of_node}}.yaml"
