---
  - block:
    - name: Disable Centos6 Firewall 1 (For testing purposes only)
      service: name=iptables state=stopped

    - name: Disable Centos6 Firewall 2 (For testing purposes only)
      command: chkconfig iptables off
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

  - name: Include "{{ansible_os_family}}" Torque recipe
    include: "{{ansible_os_family}}.yaml"

  - name: Set the Torque server name
    copy: content=torqueserver dest=/etc/torque/server_name

  - name: Include "{{torque_type_of_node}}" Torque recipe
    include: "{{torque_type_of_node}}.yaml"
