---
  - name: Set RedHat facts
    set_fact:
      TORQUE_PATH: "/var/lib/torque"
      TORQUE_SERVICE: "pbs_server"
      SCHED_SERVICE: "pbs_sched"
      MOM_SERVICE: "pbs_mom"

  - name: Set Centos 6 facts
    set_fact:
      TORQUE_PKG_VERSION: "4.2.10-5.el6"
      PKG_FOLDER: "centos6"
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

  - name: Set Centos 7 facts
    set_fact:
      TORQUE_PKG_VERSION: "4.2.10-5.el7"
      PKG_FOLDER: "centos7"
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

  - name: Add epel repo
    yum: name=epel-release,openssh-clients

  - name: Yum install PIP
    yum: name=python-pip

  - name: Copy required packages
    copy: src={{PKG_FOLDER}}/{{item}} dest=/tmp/{{item}}
    with_items:
      - torque-{{TORQUE_PKG_VERSION}}.x86_64.rpm
      - torque-client-{{TORQUE_PKG_VERSION}}.x86_64.rpm
      - torque-libs-{{TORQUE_PKG_VERSION}}.x86_64.rpm
      - torque-devel-{{TORQUE_PKG_VERSION}}.x86_64.rpm
      - torque-scheduler-{{TORQUE_PKG_VERSION}}.x86_64.rpm
      - torque-server-{{TORQUE_PKG_VERSION}}.x86_64.rpm
      - torque-mom-{{TORQUE_PKG_VERSION}}.x86_64.rpm

  - name: Install rpm torque packages (common)
    yum:
      name:
        - "/tmp/torque-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
        - "/tmp/torque-client-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
        - "/tmp/torque-libs-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
      state: present

  - name: Install rpm torque packages (front)
    yum:
      name:
        - "/tmp/torque-devel-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
        - "/tmp/torque-scheduler-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
        - "/tmp/torque-server-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
      state: present
    when: torque_type_of_node == "front"

  - name: Install rpm torque packages (wn)
    yum:
      name:
        - "/tmp/torque-mom-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
      state: present
    when: torque_type_of_node == "wn"
