---
  - name: Set RedHat facts
    set_fact:
      PBS_PATH: "/var/spool/pbs"
      PBS_SERVICE: "pbs"
      SCHED_SERVICE: "pbs_sched"
      MOM_SERVICE: "pbs"

  - name: Add epel repo
    yum: name=epel-release,openssh-clients,unzip
    
  - name: Download openpbs
    ansible.builtin.get_url:
      url: https://vcdn.altair.com/rl/OpenPBS/rockylinux/openpbs_22.05.11.rockylinux_8.5.zip
      dest: /tmp/openpbs_22.05.11.rockylinux_8.5.zip
    
  - name: Extract openpbs
    ansible.builtin.unarchive:
      src: /tmp/openpbs_22.05.11.rockylinux_8.5.zip
      dest: /tmp/

  - name: Install rpm pbs packages (front)
    yum:
      name:
        - "/tmp/openpbs_22.05.11.rockylinux_8.5/openpbs-server-22.05.11-0.x86_64.rpm"
      state: present
      disable_gpg_check: true
    when: pbs_type_of_node == "front"

  - name: Install rpm pbs packages (wn)
    yum:
      name:
        - "/tmp/openpbs_22.05.11.rockylinux_8.5/openpbs-execution-22.05.11-0.x86_64.rpm"
      state: present
      disable_gpg_check: true
    when: pbs_type_of_node == "wn"
