---
  - name: Set RedHat facts
    set_fact:
      TORQUE_PATH: "/var/lib/torque"
      TORQUE_SERVICE: "pbs_server"
      SCHED_SERVICE: "pbs_sched"
      MOM_SERVICE: "pbs_mom"

  - name: Add epel repo
    yum: name=epel-release,openssh-clients,unzip
    
  - name: Download openpbs
    ansible.builtin.get_url:
      url: https://vcdn.altair.com/rl/OpenPBS/rockylinux/openpbs_22.05.11.rockylinux_8.5.zip
      dest: /tmp/openpbs_22.05.11.rockylinux_8.5.zip
    
  - name: Extract openpbs
    ansible.builtin.unarchive:
      src: /tmp/openpbs_22.05.11.rockylinux_8.5.zip
      dest: /tmp/

  - name: Install rpm torque packages (common)
    yum:
      name:
        - "/tmp/torque-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
        - "/tmp/torque-client-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
        - "/tmp/torque-libs-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
      state: present

  - name: Install rpm torque packages (front)
    yum:
      name:
        - "/tmp/torque-devel-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
        - "/tmp/torque-scheduler-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
        - "/tmp/torque-server-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
      state: present
    when: torque_type_of_node == "front"

  - name: Install rpm torque packages (wn)
    yum:
      name:
        - "/tmp/torque-mom-{{TORQUE_PKG_VERSION}}.x86_64.rpm"
      state: present
    when: torque_type_of_node == "wn"
