---
  - name: Create the mom_priv/config file
    copy:
      dest: "{{TORQUE_PATH}}/mom_priv/config"
      content: |
          $clienthost torqueserver
          $max_conn_timeout_micro_sec 10000
          $mom_host {{IM_NODE_HOSTNAME}}
      mode: 0644
      owner: root
      group: root

  - name: Restart Torque server
    service: name={{TORQUE_SERVICE}} state=restarted pattern=/usr/sbin/pbs_server

  - name: Set the Torque server name
    service: name={{TORQUE_SERVICE}} state=started pattern=/usr/sbin/pbs_server

  - name: Set the Torque server name
    shell: echo "{{PBS_SERVER_CONF}}" | qmgr creates={{TORQUE_PATH}}/server_priv/queues/batch

  - name: Set the Torque server name
    service: name={{SCHED_SERVICE}} state=started pattern=/usr/sbin/pbs_sched

  # Many times TORQUE_SERVICE and SCHED_SERVICE do not start properly. Wait and test them again
  - name: Set the Torque server name
    command: sleep 5

  - name: Set the Torque server name
    service: name={{SCHED_SERVICE}} state=started pattern=/usr/sbin/pbs_sched

  - name: Set the Torque server name
    service: name={{TORQUE_SERVICE}} state=started pattern=/usr/sbin/pbs_server
