---
  - name: set hostname
    command: hostname {{IM_NODE_HOSTNAME}} 

  - name: Create the mom_priv/config file
    copy:
      dest: "{{PBS_PATH}}/mom_priv/config"
      content: |
          $clienthost pbsserver
      mode: 0644
      owner: root
      group: root

  - name: Start "{{MOM_SERVICE}}" service
    service: name="{{MOM_SERVICE}}" state=started
  # Many times MOM_SERVICE does not start properly. Wait and test it again
  - name: Sleep 5 seconds
    command: sleep 5
  - name: Start "{{MOM_SERVICE}}" service (again)
    service: name="{{MOM_SERVICE}}" state=started
